/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/Administrative/admin_pending': RouteRecordInfo<'/admin/Administrative/admin_pending', '/admin/Administrative/admin_pending', Record<never, never>, Record<never, never>>,
    '/admin/Administrative/admin_table': RouteRecordInfo<'/admin/Administrative/admin_table', '/admin/Administrative/admin_table', Record<never, never>, Record<never, never>>,
    '/admin/Administrative/table_admin': RouteRecordInfo<'/admin/Administrative/table_admin', '/admin/Administrative/table_admin', Record<never, never>, Record<never, never>>,
    '/admin/Administrative/verified': RouteRecordInfo<'/admin/Administrative/verified', '/admin/Administrative/verified', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/inspection_report/report_approved': RouteRecordInfo<'/admin/inspection_report/report_approved', '/admin/inspection_report/report_approved', Record<never, never>, Record<never, never>>,
    '/admin/inspection_report/report_pending': RouteRecordInfo<'/admin/inspection_report/report_pending', '/admin/inspection_report/report_pending', Record<never, never>, Record<never, never>>,
    '/admin/inspection_report/report_table': RouteRecordInfo<'/admin/inspection_report/report_table', '/admin/inspection_report/report_table', Record<never, never>, Record<never, never>>,
    '/admin/inspector/architectural/architectural_table': RouteRecordInfo<'/admin/inspector/architectural/architectural_table', '/admin/inspector/architectural/architectural_table', Record<never, never>, Record<never, never>>,
    '/admin/inspector/architectural/report': RouteRecordInfo<'/admin/inspector/architectural/report', '/admin/inspector/architectural/report', Record<never, never>, Record<never, never>>,
    '/admin/inspector/electrical/electrical_table': RouteRecordInfo<'/admin/inspector/electrical/electrical_table', '/admin/inspector/electrical/electrical_table', Record<never, never>, Record<never, never>>,
    '/admin/inspector/inspector_login': RouteRecordInfo<'/admin/inspector/inspector_login', '/admin/inspector/inspector_login', Record<never, never>, Record<never, never>>,
    '/admin/inspectors_schedule/data_table': RouteRecordInfo<'/admin/inspectors_schedule/data_table', '/admin/inspectors_schedule/data_table', Record<never, never>, Record<never, never>>,
    '/admin/inspectors_schedule/schedule_approved': RouteRecordInfo<'/admin/inspectors_schedule/schedule_approved', '/admin/inspectors_schedule/schedule_approved', Record<never, never>, Record<never, never>>,
    '/admin/inspectors_schedule/schedule_mix': RouteRecordInfo<'/admin/inspectors_schedule/schedule_mix', '/admin/inspectors_schedule/schedule_mix', Record<never, never>, Record<never, never>>,
    '/applicant/about': RouteRecordInfo<'/applicant/about', '/applicant/about', Record<never, never>, Record<never, never>>,
    '/applicant/home': RouteRecordInfo<'/applicant/home', '/applicant/home', Record<never, never>, Record<never, never>>,
    '/applicant/login': RouteRecordInfo<'/applicant/login', '/applicant/login', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/applicant_portal': RouteRecordInfo<'/applicant/occupancy_permit/applicant_portal', '/applicant/occupancy_permit/applicant_portal', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/completion_forms': RouteRecordInfo<'/applicant/occupancy_permit/completion_forms', '/applicant/occupancy_permit/completion_forms', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/cfei': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/cfei', '/applicant/occupancy_permit/occupancy_forms/cfei', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/coc': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/coc', '/applicant/occupancy_permit/occupancy_forms/coc', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/mc': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/mc', '/applicant/occupancy_permit/occupancy_forms/mc', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/unified': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/unified', '/applicant/occupancy_permit/occupancy_forms/unified', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/statuses/notification': RouteRecordInfo<'/applicant/occupancy_permit/statuses/notification', '/applicant/occupancy_permit/statuses/notification', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/statuses/status_one': RouteRecordInfo<'/applicant/occupancy_permit/statuses/status_one', '/applicant/occupancy_permit/statuses/status_one', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/upload': RouteRecordInfo<'/applicant/occupancy_permit/upload', '/applicant/occupancy_permit/upload', Record<never, never>, Record<never, never>>,
    '/applicant/services': RouteRecordInfo<'/applicant/services', '/applicant/services', Record<never, never>, Record<never, never>>,
  }
}
