/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/building_inspection/approved_status': RouteRecordInfo<'/admin/building_inspection/approved_status', '/admin/building_inspection/approved_status', Record<never, never>, Record<never, never>>,
    '/admin/building_inspection/inspection_schedule': RouteRecordInfo<'/admin/building_inspection/inspection_schedule', '/admin/building_inspection/inspection_schedule', Record<never, never>, Record<never, never>>,
    '/admin/building_inspection/mix_status': RouteRecordInfo<'/admin/building_inspection/mix_status', '/admin/building_inspection/mix_status', Record<never, never>, Record<never, never>>,
    '/admin/building_inspection/report/bi_report': RouteRecordInfo<'/admin/building_inspection/report/bi_report', '/admin/building_inspection/report/bi_report', Record<never, never>, Record<never, never>>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/applicant/about': RouteRecordInfo<'/applicant/about', '/applicant/about', Record<never, never>, Record<never, never>>,
    '/applicant/home': RouteRecordInfo<'/applicant/home', '/applicant/home', Record<never, never>, Record<never, never>>,
    '/applicant/login': RouteRecordInfo<'/applicant/login', '/applicant/login', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/applicant_portal': RouteRecordInfo<'/applicant/occupancy_permit/applicant_portal', '/applicant/occupancy_permit/applicant_portal', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/completion_forms': RouteRecordInfo<'/applicant/occupancy_permit/completion_forms', '/applicant/occupancy_permit/completion_forms', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/cfei': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/cfei', '/applicant/occupancy_permit/occupancy_forms/cfei', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/coc': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/coc', '/applicant/occupancy_permit/occupancy_forms/coc', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/mc': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/mc', '/applicant/occupancy_permit/occupancy_forms/mc', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/occupancy_forms/unified': RouteRecordInfo<'/applicant/occupancy_permit/occupancy_forms/unified', '/applicant/occupancy_permit/occupancy_forms/unified', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/statuses/notification': RouteRecordInfo<'/applicant/occupancy_permit/statuses/notification', '/applicant/occupancy_permit/statuses/notification', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/statuses/status_one': RouteRecordInfo<'/applicant/occupancy_permit/statuses/status_one', '/applicant/occupancy_permit/statuses/status_one', Record<never, never>, Record<never, never>>,
    '/applicant/occupancy_permit/upload': RouteRecordInfo<'/applicant/occupancy_permit/upload', '/applicant/occupancy_permit/upload', Record<never, never>, Record<never, never>>,
    '/applicant/services': RouteRecordInfo<'/applicant/services', '/applicant/services', Record<never, never>, Record<never, never>>,
  }
}
